### ISSUE TITLE
reconstruction data

### ISSUE THREAD

**Issue by ForrestPi** [legel/3co#3]
Hi, could you provide the data for reconstruction?

**Comment by legel** [comment]
Hi @ForrestPi thank you for your interest in our 3D reconstruction data.

I have decided to open source a small challenge dataset of 8 high-resolution iPhone Pro 3D scans, including the original dataset that was used to produce the 3D model currently at https://3co.ai (first .zip below).

Note all of the .zip files are very large (several gigabytes), so I recommend just starting with one.  They contain raw data from the iPhone which can be processed with scripts in our reconstruction directory.

### 3D Scanned Data Set of 8 Plants from iPhone Pro with LiDAR
1. https://storage.googleapis.com/3co_scans/alocasia_baginda.zip
2. https://storage.googleapis.com/3co_scans/bonsai_tree.zip
3. https://storage.googleapis.com/3co_scans/cactus.zip 
4. https://storage.googleapis.com/3co_scans/cycad.zip
5. https://storage.googleapis.com/3co_scans/ficus.zip
6. https://storage.googleapis.com/3co_scans/orchid.zip
7. https://storage.googleapis.com/3co_scans/palm.zip
8. https://storage.googleapis.com/3co_scans/philodendron.zip
